# Generated by Django 2.2.6 on 2019-10-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('Atlantic', 'Atlantic'), ('Metropolitan', 'Metropolitan'), ('Pacific', 'Pacific'), ('Central', 'Central')], max_length=50, null=True),
        ),
    ]
