# Generated by Django 2.2.6 on 2019-10-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teamrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamrecords',
            name='streak_type',
            field=models.CharField(max_length=10),
        ),
    ]
