# Generated by Django 2.2.6 on 2019-10-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20191010_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamrecords',
            options={'ordering': ('-points',)},
        ),
    ]
