# Generated by Django 2.2.6 on 2019-10-15 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0006_auto_20191015_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=100)),
                ('game_pk', models.IntegerField()),
                ('link', models.URLField()),
                ('final_score_home', models.IntegerField(blank=True, null=True)),
                ('final_score_away', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField()),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_game', to='teams.Team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_game', to='teams.Team')),
            ],
        ),
    ]
