# Generated by Django 2.2.6 on 2019-10-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
