# Generated by Django 2.2.6 on 2019-10-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20191017_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
