# Generated by Django 2.2.6 on 2019-11-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0006_auto_20191015_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nhl_api_id', models.IntegerField()),
                ('jersey_number', models.IntegerField()),
                ('position_code', models.CharField(max_length=1)),
                ('position_name', models.CharField(max_length=31)),
                ('position_type', models.CharField(choices=[('Forward', 'Forward'), ('Defenceman', 'Defenceman'), ('Goalie', 'Goalie')], max_length=31)),
                ('position_abbv', models.CharField(max_length=3)),
                ('current_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='teams.Team')),
            ],
        ),
    ]
