# Generated by Django 2.2.6 on 2019-12-05 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20191115_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('toi', models.CharField(max_length=20)),
                ('assists', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('points', models.IntegerField()),
                ('pim', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('games', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('pp_goals', models.IntegerField()),
                ('pp_pts', models.IntegerField()),
                ('pp_toi', models.CharField(max_length=20)),
                ('ev_toi', models.CharField(max_length=20)),
                ('face_off_pct', models.FloatField()),
                ('shot_pct', models.FloatField()),
                ('gwg', models.IntegerField()),
                ('ot_goals', models.IntegerField()),
                ('sh_goals', models.IntegerField()),
                ('sh_points', models.IntegerField()),
                ('sh_toi', models.CharField(max_length=20)),
                ('blocked_shots', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('shifts', models.IntegerField()),
                ('toi_per_gm', models.CharField(max_length=20)),
                ('ev_toi_per_gm', models.CharField(max_length=20)),
                ('sh_toi_per_gm', models.CharField(max_length=20)),
                ('pp_toi_per_gm', models.CharField(max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statline', to='players.Player')),
            ],
        ),
    ]
