# Generated by Django 2.2.6 on 2019-12-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
