# Generated by Django 2.2.6 on 2019-12-05 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20191205_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='gaa',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
